# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Dennis Tran
tagline:          'portfolio'
description:      'Data Scientist'
url:              https://dennisdt.github.io/
baseurl:          /

author:
  name:           'Dennis Tran'
  url:            https://www.linkedin.com/in/dennisdt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dennisdt/